### ISSUE TITLE
Narrator Training

### ISSUE THREAD

**Issue by Flaick** [facebookresearch/LaViLa#12]
Hello, thank you very much for this excellent work, though I am wondering if you plan to public the training pipeline of LLM-based narrator?

**Comment by zhaoyue-zephyrus** [comment]
Hi @Flaick ,

 Please check out [this section](https://github.com/facebookresearch/LaViLa/blob/main/docs/PRETRAIN.md#training-and-evaluating-narrator) about the training details of Narrator. 

Best,
Yue

**Comment by Flaick** [comment]
Thanks for the help, I missed that part!
