### ISSUE TITLE
The pretraining weights of TSF-B/L (visual only) on EPIC-KITCHENS-100 and EGTEA.  

### ISSUE THREAD

**Issue by daiguangzhao** [facebookresearch/LaViLa#18]
Thank you and your team for your contribution. Thanks for contributing such a complete and detailed code. I would like to use your code as my work's codebase. Would you mind providing the pre-training weights on IN-21k+K400 in Table 4 and Table 9 utilizing only TSF-B/L (visual only).

**Comment by zhaoyue-zephyrus** [comment]
Hi @daiguangzhao ,

We used the checkpoint in https://github.com/facebookresearch/TimeSformer/tree/main#model-zoo and patch the codebase with TimeSformer's model without modification (please find more details at https://github.com/facebookresearch/TimeSformer/blob/main/timesformer/models/vit.py#L338).

Best,
Yue
