### ISSUE TITLE
The pre-training weights of Dual-Encoder Baseline (with TSF-B/L)

### ISSUE THREAD

**Issue by daiguangzhao** [facebookresearch/LaViLa#20]
Thanks so much to the authors for their contributions to the egocentric community!  I wanted to use your excellent code as my codebase in my work, but after I removed the pre-training weights (clip_openai_timesformer_base.narrator_rephraser.ep_0005.md5sum_d73a9c.pth), the performance of epic100 became very bad. Therefore, would you mind providing the pre-training weights for Dual-Encoder Baseline (with TSF-B/L)? Thanks a lot!

**Comment by zhaoyue-zephyrus** [comment]
Hi @daiguangzhao ,

 Please take a look at [MODEL_ZOO.md#narrator](https://github.com/facebookresearch/LaViLa/blob/main/docs/MODEL_ZOO.md#narrator). The second column from the right should hopefully work.

 Best,
Yue

**Comment by daiguangzhao** [comment]
thanks for your reply! Thanks again for your excellent contribution to the ego community.
