### ISSUE TITLE
val .pkl files for pre-training LAVILA Dual-Encoder

### ISSUE THREAD

**Issue by AlbertHuyb** [facebookresearch/LaViLa#34]
Dear authors,

Thanks for your brilliant work!

I'd like to re-produce the pre-training of LAVILA Dual-Encoder, but only find the `.pkl` files to construct training datasets. In `main_pretrain.py`, we can see that the pre-training code also requires `.pkl` files for val datasets, like `ego4d_val.rephraser.no_punkt_top3.pkl` and `ego4d_val.narrator_63690737.return_10.pkl`. 

How could I get these `.pkl` files? 

Thanks!

**Comment by zhaoyue-zephyrus** [comment]
Hi @AlbertHuyb 

Please take a look at [this doc](https://github.com/facebookresearch/LaViLa/blob/main/docs/PRETRAIN.md) and in particular [the narrating section](https://github.com/facebookresearch/LaViLa/blob/main/docs/PRETRAIN.md#narrating-video-clips-using-lavila-narrator) and [rephrasing section](https://github.com/facebookresearch/LaViLa/blob/main/docs/PRETRAIN.md#rephrasing-human-narrations-using-lavila-rephraser).

Best,
Yue

**Comment by AlbertHuyb** [comment]
Thanks!
