### ISSUE TITLE
Resized Version of EK100

### ISSUE THREAD

**Issue by SJTUwxz** [facebookresearch/LaViLa#7]
Hi,

Thank you for this amazing work!

I saw "(Recommended) The raw videos are huge (~1 TB). As an alternative, please check out a resized version" in DATASET readme, but the link to resized version seems to be pointing back to the readme file. I wonder if there is a specific download link to get "video_ht256px".

Thanks again!

**Comment by zhaoyue-zephyrus** [comment]
Hi @SJTUwxz ,

 Thanks for spotting this! Please check out the [latest commit](https://github.com/facebookresearch/LaViLa/commit/62f89c47253952afc4adf14c13b4fafbeee99a1e) for the fix.

Best,
Yue

**Comment by wolfworld6** [comment]
> Hi @SJTUwxz ,
> 
> Thanks for spotting this! Please check out the [latest commit](https://github.com/facebookresearch/LaViLa/commit/62f89c47253952afc4adf14c13b4fafbeee99a1e) for the fix.
> 
> Best, Yue

I wanna know ， Is the shortest side 256 p? thx

**Comment by zhaoyue-zephyrus** [comment]
> > Hi @SJTUwxz ,
> > Thanks for spotting this! Please check out the [latest commit](https://github.com/facebookresearch/LaViLa/commit/62f89c47253952afc4adf14c13b4fafbeee99a1e) for the fix.
> > Best, Yue
> 
> I wanna know ， Is the shortest side 256 p? thx

@wolfworld6  Yes it is.
