### ISSUE TITLE
Thank you for contributing such excellent work!

### ISSUE THREAD

**Issue by daiguangzhao** [facebookresearch/LaViLa#8]
Thank you and your team for your contribution, this is the most complete and carefully documented work I have seen to date on the usage guidelines, including the installation environment, the delicate partitioning of the dataset, the pre-training weights (key) and the training and testing scripts. As a result, I think your work is very convincing in the whole field of video understanding.

**Comment by zhaoyue-zephyrus** [comment]
Thank you for the praise :) I'll close it and answer your issue in the other post.
